// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiyntxqqpuitrzorgdtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpeW50eHFxcHVpdHJ6b3JnZHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODkyMzgsImV4cCI6MjA2Njg2NTIzOH0.Qjh7gi2308Zs4eELAYc06HSrsqW_z3rF4u6ZLpcd10A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});